# Generated by Django 4.0.3 on 2022-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='login',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
