# Generated by Django 3.2.12 on 2022-05-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_personal_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='ability',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainApp.categories'),
        ),
    ]
