# Generated by Django 4.0.3 on 2022-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20220519_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='password',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
